config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/tv_shows', to: 'tv_shows#index'
  get '/welcome', to: 'pages#welcome'
  post '/tv_shows', to: 'tv_shows#create'
 # root 'pages#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
    # before_save :capitalize_name

    validates :name, presence: true
    validates :name, length: { minimum: 5 }
    validates :name, uniqueness: true

    private
    def capitalize_name
        splited_names = self.name.split # ~> ["game", "of", "thrones"]
        capitalized_words = splited_names.map { |splited_name| splited_name.capitalize } # ~> ["Game", "Of", "Thrones"]
        self.name = capitalized_words.join(' ') # ~> "Game Of Thrones"
    end
    belongs_to :user
end

app/models/tv_shows.rb
class TvShow < ApplicationRecord
    before_save :capitalize_name

    private
    def capitalize_name
        splited_names = self.name.split # ~> ["game", "of", "thrones"]
        capitalized_words = splited_names.map { |splited_name| splited_name.capitalize } # ~> ["Game", "Of", "Thrones"]
        self.name = capitalized_words.join(' ') # ~> "Game Of Thrones"
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tv_shows, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def welcome
    end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  
  
  
  def index
    @tv_shows = TvShow.all
    #@search = params[:query]
  end

  def create
    @tv_show = TvShow.new(tv_show_params)
    @tv_show.save
    redirect_to tv_shows_path 
  end

  private

  def tv_show_params
      params.require(:tv_show).permit(:name, :summary, :release_date, :rating)
  end

  before_action :authenticate_user!, except: %i[index]

  # ...

  # GET /tv_shows/new

  def create
      @tv_show = current_user.tv_shows.build(tv_show_params)
      # ...
  end

end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFavoriteTvSeries</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <br>
    <div class="container-fluid">
    <button type="button" class="btn-primary">Primary</button>
    </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/welcome.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="display-4 text-success">My Favorite TV series</h1>
            <p class="lead text-secondary">Welcome!!!</p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            <div class="media">
                <%= image_tag('iron-man.jpg', size: "64x64", alt: "Iron Man", class: 'mr-3')%>
                <div class="media-body">
                    <h5 class="mt-0">Iron Man</h5>
                    2008's Iron Man tells the story of Tony Stark, a billionaire industrialist and genius inventor who is kidnapped and forced to build a devastating weapon. Instead, using his intelligence and ingenuity, Tony builds a high-tech suit of armor and escapes captivity.
                </div>
            </div>
        </div>
    </div>
</div>

app/views/tv_shows/index.html.erb
<h1 class="titulo-series">Nativaleathers</h1>
<hr>
<h3>Ingrese una serie o película nueva</h3>

<%= form_with model: TvShow.new do |form| %>
    <%= form.text_field :name %><br>
    <%= form.text_area :summary %><br>
    <%= form.date_field :release_date %><br>
    <%= form.number_field :rating, step: '0.1' %><br>
    <%= form.submit  "Enviar" %>
<% end %>

<%= "Mi nombre es: #{ @search || "***ningun dato ingresado***" }" %>
<hr>
<%= link_to 'go back to welcome page', welcome_path %>

<%= link_to 'Search tv show', welcome_path %>

<html>
    <head>
        <title>MyFavoriteTvSeriesM9</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <% if user_signed_in? %>
            <div>
                <p>Bienvenido <%= current_user.email %>!!</p>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            </div>
        <% else %>
            <div>
                <%= link_to 'Sign up', new_user_registration_path %> |
                <%= link_to 'Log in', new_user_session_path %>
            </div>
        <% end %>
        <%= yield %>
    </body>
<!--...-->
    <tbody>
        <% @tv_shows.each do |tv_show| %>
            <tr>
                <!--...-->
                <% if user_signed_in? %>
                    <td><%= link_to 'Show', tv_show %></td>
                <% end %>
                <% if (user_signed_in? && (current_user == tv_show.user)) %>
                    <td><%= link_to 'Edit', edit_tv_show_path(tv_show) %></td>
                    <td><%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<% if user_signed_in? %>
    <%= link_to 'New Tv Show', new_tv_show_path %>
<% end %>
    
</html>